#!/usr/bin/python3

import subprocess
import os

try:
    command = "clang -Wall -Wextra --debug -o main main.c"
    completed = subprocess.run(command, shell=True, check=True)
except Exception as e:
    print("Error while compiling the program!", e)

outdir = "output"
if not os.path.exists(outdir):
    os.makedirs(outdir)

indir = "input"
files = os.listdir("input")

for file in files:
    try:
        s = file.split(".")
        v = os.path.join(indir, file)
        args = ["./main", v, s[0] + "_" + s[1] + ".bmp"]

        path = os.path.join(outdir, args[2])

        subprocess.run(args, check=True)

        # move output file to outputdir
        os.rename(args[2], path)
    except Exception as e:
        print("Error running the program!", e)
